export default {
  index: "/",
  login: "/account/login",
  register: "/account/register",
  verifyEmail: "/account/verify-email",
  forgotPassword: "/account/forgot-password",
  resetPassword: "/account/reset-password",
  subsribers: "/admin/subscribers",
  users: "/admin/users",
  importUsers: "/admin/importusers",
  expenses: "/admin/expenses",
  addEditUsers: "/admin/users/add",
  plans: "/billing/plans",
  invoices: "/billing/invoices",
};
