export default {
  SUCCESSFUL_LOGIN: "SUCCESSFUL_LOGIN",
  PERFORM_LOGOUT: "PERFORM_LOGOUT",
  FILL_LANGUAGES: "FILL_LANGUAGES",
  LOADING: "LOADING",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
  SEARCHING: "SEARCHING",
  LOAD_SUBSCRIBERS: "LOAD_SUBSCRIBERS",
  TOGGLE_MENU: "TOGGLE_MENU",
  ADD_SUBSCRIBER: "ADD_SUBSCRIBER",
};
